let ds=JSON.parse(localStorage.getItem('disney-attractions-v2')||'{}');
const tagName={must:'⭐ Must Ride',hot:'🔥 ฮิตมาก',thrill:'🎢 Thrill',family:'👨‍👩‍👧 Family'};
function rideCard(r,featured=false){const k='hongkong:'+r.id,v=ds[k]||{};return `<article class="ride ${featured?'recommended':''}" data-ride="${r.id}">${r.img?`<img class="rideimg" src="${r.img}" alt="${r.n}" loading="lazy" onerror="this.onerror=null;this.src='${IMG.d2}'">`:''}<div class="ridebody"><div class="ridezone">${r.z}</div><h4>${r.n}</h4><div class="tags">${(r.cat||[]).map(c=>`<span class="tag ${c}">${tagName[c]}</span>`).join('')}</div>${r.source?`<a class="photo-credit" target="_blank" href="${r.source}">ภาพจริง • Wikimedia Commons</a>`:''}<div class="rideflags"><button class="toggle want ${v.want?'on':''}" data-k="${k}" data-type="want">⭐ อยากเล่น</button><button class="toggle done ${v.done?'on':''}" data-k="${k}" data-type="done">✅ เล่นแล้ว</button></div></div></article>`}
function matchFilter(r,f){return f==='all'||(r.cat||[]).includes(f)}
function disneyHTML(){const featured=rides.filter(r=>['frozen-ever','mystic','big-grizzly'].includes(r.id));return `<section class="disneybox" id="disney"><div class="disneytop"><div><div class="ey">DISNEY CHECKLIST • ${rides.length} ITEMS</div><h3>🎢 เครื่องเล่น Hong Kong Disneyland</h3><div class="small muted">รูปจริงของตัวฮิต • ป้าย Must Ride / ฮิตมาก • เลือกดูตามสไตล์ได้ทันที</div></div><div class="meter"><span id="rideCount">0/${rides.length}</span><div class="track"><i id="rideBar"></i></div></div></div><div class="reco-title">🔥 ตัวฮิตที่ควรเก็บก่อน</div><div class="reco">${featured.map(r=>rideCard(r,true)).join('')}</div><div class="reco-title">🎠 เลือกดูตามสไตล์</div><div class="filters" id="rideFilters"><button class="filterbtn on" data-filter="all">ทั้งหมด</button><button class="filterbtn" data-filter="must">⭐ Must Ride</button><button class="filterbtn" data-filter="hot">🔥 ฮิตมาก</button><button class="filterbtn" data-filter="thrill">🎢 Thrill</button><button class="filterbtn" data-filter="family">👨‍👩‍👧 Family</button></div><div class="rides" id="rideList">${rides.map(r=>rideCard(r)).join('')}</div><div class="hint">↔ ปัดเพื่อดูเครื่องถัดไป • เช็กเวลารอและเวลาปิดเครื่องเล่นจากแอปวันจริงอีกครั้ง</div></section>`}
function renderFilter(f='all'){const fbox=document.getElementById('rideFilters');if(!fbox)return;fbox.querySelectorAll('.filterbtn').forEach(b=>b.classList.toggle('on',b.dataset.filter===f));document.getElementById('rideList').innerHTML=rides.filter(r=>matchFilter(r,f)).map(r=>rideCard(r)).join('')}
function meter(){const n=rides.filter(r=>ds['hongkong:'+r.id]?.done).length;if(document.getElementById('rideCount'))document.getElementById('rideCount').textContent=`${n}/${rides.length}`;if(document.getElementById('rideBar'))document.getElementById('rideBar').style.width=(n/rides.length*100)+'%'}

const hotelImg={silkaFar:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',ramada:'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80',silkaTsuen:'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',dorsett:'https://assets.st-note.com/img/1745328529-Z9TjISerHVcN6olJ5mFRXzst.jpg?width=1200'};
const HOTEL_DATA={
 silkaFar:{name:'Silka Far East Hotel',loc:'Tsuen Wan • ใกล้ Tsuen Wan MTR',star:'3-star hotel',img:hotelImg.silkaFar,map:'https://www.google.com/maps/search/?api=1&query=Silka+Far+East+Hotel+Hong+Kong',hkd:323,thb:1350,five:6750,four:5400,checked:'30–31 Aug 2026',source:'Google Hotels',desc:'ถูกสุดในชุดนี้ แต่ต้องแลกกับการอยู่ไกล Jordan / Tsim Sha Tsui กว่า'},
 ramada:{name:'Ramada Grand Tsim Sha Tsui',loc:'23 Austin Avenue • ใกล้ Jordan MTR',star:'4-star hotel',img:hotelImg.ramada,map:'https://www.google.com/maps/search/?api=1&query=Ramada+Grand+Tsim+Sha+Tsui',hkd:435,thb:1820,five:9100,four:7300,checked:'30–31 Aug 2026',source:'Hotels.com',desc:'ทำเลสะดวกกว่า Tsuen Wan ชัดเจน เหมาะกับแผน Jordan / TST / Central มากกว่า'},
 silkaTsuen:{name:'Silka Tsuen Wan, Hong Kong',loc:'Kwai Chung / Tsuen Wan',star:'4-star hotel',img:hotelImg.silkaTsuen,map:'https://www.google.com/maps/search/?api=1&query=Silka+Tsuen+Wan+Hong+Kong',hkd:437,thb:1825,five:9125,four:7300,checked:'30–31 Aug 2026',source:'Google Hotels',desc:'โรงแรมเต็มรูปแบบ 4 ดาว ราคาใกล้ Ramada แต่ทำเลออกมาทาง Tsuen Wan มากกว่า'},
 dorsett:{name:'Dorsett Mongkok, Hong Kong',loc:'88 Tai Kok Tsui Road • Olympic MTR',star:'4-star hotel',img:hotelImg.dorsett,map:'https://www.google.com/maps/search/?api=1&query=Dorsett+Mongkok+Hong+Kong',hkd:542,thb:2265,five:11315,four:9050,checked:'31 Aug–1 Sep 2026',source:'Dorsett Official via Google Hotels',desc:'เกินเป้าไม่มาก จึงยังเก็บไว้เป็นตัวเลือกหลัก เพราะคุณภาพ/บรรยากาศดีกว่าตัวประหยัดหลายแห่ง'}
};
function priceBox(h){return `<div class="sidebox"><b>💰 ราคาที่พบล่าสุด: HK$${h.hkd.toLocaleString()} / คืน</b><div class="small muted">≈ ฿${h.thb.toLocaleString()} / คืน • รวม taxes + fees • ${h.source} • ${h.checked}</div><div class="small"><b>5 คืน ≈ ฿${h.five.toLocaleString()}</b> • 4 คืน ≈ ฿${h.four.toLocaleString()}</div></div>`}
function hotelCard(h){return `<article class="card hotelcard"><img src="${h.img}" alt="${h.name}"><div class="pad"><div class="ey">${h.ey}</div><h3>${h.name}</h3><p>${h.loc}</p><div class="hotelmeta"><span class="badge ${h.cls}">${h.badge}</span><span class="badge">${h.star}</span></div>${priceBox(h)}<div class="muted small">${h.desc}</div><a class="map" target="_blank" href="${h.map}">📍 Location</a></div></article>`}
function withMode(key,is5,ey,cls,badge){return {...HOTEL_DATA[key],ey,cls,badge}}
function renderHotels(is5){const list=is5?[
 withMode('ramada',true,'BEST 5D4N CENTRAL PICK','good','★ 4 คืน ≈ 7.3K'),
 withMode('silkaFar',true,'SAFEST BUDGET','good','✓ 4 คืน ≈ 5.4K'),
 withMode('silkaTsuen',true,'4-STAR BUDGET','good','✓ 4 คืน ≈ 7.3K'),
 withMode('dorsett',true,'SAVED PREFERENCE • SLIGHTLY OVER','watch','เกินเป้า ≈ 1.05K / 4 คืน')
]:[
 withMode('silkaFar',false,'BEST 6D5N BUDGET FIT','good','✓ 5 คืน ≈ 6.75K'),
 withMode('ramada',false,'CENTRAL VALUE','good','✓ 5 คืน ≈ 9.1K'),
 withMode('silkaTsuen',false,'4-STAR BUDGET','good','✓ 5 คืน ≈ 9.13K'),
 withMode('dorsett',false,'SAVED PREFERENCE • SLIGHTLY OVER','watch','เกินเป้า ≈ 1.3K / 5 คืน')
];document.querySelector('.staygrid').innerHTML=list.map(hotelCard).join('')}

let mode=localStorage.getItem('hk-trip-mode')||'6d5n';
function renderTrip(){const is5=mode==='5d4n',D=is5?D5:D6;document.querySelectorAll('.modebtn').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));document.getElementById('navTitle').textContent=is5?'🇭🇰 Hong Kong 5D4N':'🇭🇰 Hong Kong 6D5N';document.getElementById('heroDates').textContent=is5?'วันที่ 5–9 • 5 Days 4 Nights':'วันที่ 5–10 • 6 Days 5 Nights';document.getElementById('hotelBudgetChip').textContent=is5?'🏨 Hotel target ≈ 8K / 4 nights':'🏨 Hotel target ≈ 10K / 5 nights';document.getElementById('budgetTitle').textContent=is5?'Budget target: ≈ 8,000 ฿ / 4 nights':'Budget target: ≈ 10,000 ฿ / 5 nights';document.getElementById('budgetText').textContent='ราคาเช็กล่าสุด 23 Aug 2026 • 2 คน / 1 ห้อง • รวมภาษี/ค่าธรรมเนียมตามแหล่งอ้างอิง • ยอด 4/5 คืนเป็นการคูณเรทที่พบเพื่อเทียบงบ ราคาจองจริงเปลี่ยนตามวัน';document.getElementById('itTitle').textContent=is5?'5 วัน 4 คืน • แผนแบบกระชับ':'6 วัน 5 คืน • แต่ละวัน + วิธีเดินทาง';document.getElementById('itNote').textContent=is5?'โหมด 5D4N รวม Central + Wan Chai + The Peak เป็นวันเดียว แต่ยังเก็บ Disneyland และ Ngong Ping':'โหมด 6D5N เที่ยวสบายกว่าและแยก Central / The Peak ออกจาก Ngong Ping';document.getElementById('footerMode').textContent=is5?'5 Days 4 Nights':'6 Days 5 Nights';renderHotels(is5);document.getElementById('daysbox').innerHTML=D.map((x,i)=>`<article class="card day ${i===0?'open':''}"><button class="daybtn"><img src="${IMG[x.i]}"><div><div class="ey">DAY ${i+1} • ${x.d}</div><h3>${x.t}</h3></div><span class="chev">⌄</span></button><div class="body"><div class="inside"><div class="innerpad"><img class="dayhero" src="${IMG[x.i]}"><div class="cols"><div class="timeline">${x.s.map(z=>`<div class="step"><div class="time">${z[0]}</div><div class="place">${z[1]}</div><div class="small muted">${z[3]}</div><a class="map" target="_blank" href="${M(z[2])}">📍 Location</a>${z[4]?`<button class="routebtn">${z[4]} ▾</button><div class="route"><div><div class="routecard">${z[5]}</div></div></div>`:''}</div>`).join('')}</div><div><span class="cost">💰 ${x.cost}</span><div class="sidebox"><b>🚆 Transit Tip</b><div class="small muted">เส้นทางอยู่ใต้จุดที่ใช้จริง เพื่อรู้ทันทีว่าต้องขึ้นอะไร “ตอนนี้”</div></div></div></div>${i===1?disneyHTML():''}</div></div></div></article>`).join('');meter()}
renderTrip();
document.querySelectorAll('.modebtn').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;localStorage.setItem('hk-trip-mode',mode);renderTrip();document.getElementById('stay').scrollIntoView({behavior:'smooth',block:'start'})});
document.addEventListener('click',e=>{const db=e.target.closest('.daybtn');if(db){db.parentElement.classList.toggle('open');return}const rb=e.target.closest('.routebtn');if(rb){rb.nextElementSibling.classList.toggle('open');return}const fb=e.target.closest('.filterbtn');if(fb){renderFilter(fb.dataset.filter);return}const t=e.target.closest('.toggle');if(t){ds[t.dataset.k]=ds[t.dataset.k]||{};ds[t.dataset.k][t.dataset.type]=!ds[t.dataset.k][t.dataset.type];localStorage.setItem('disney-attractions-v2',JSON.stringify(ds));document.querySelectorAll(`[data-ride="${t.closest('[data-ride]').dataset.ride}"] [data-type="${t.dataset.type}"]`).forEach(x=>x.classList.toggle('on',ds[t.dataset.k][t.dataset.type]));meter()}});meter();

const prep=['🛂 Passport','✈️ Flight / booking','🏨 Hotel booking','🎢 Disneyland ticket','🚠 Ngong Ping ticket','📱 eSIM','💳 Octopus / card','🔌 Type G adapter','🕌 Prayer items','🧥 Light jacket','☂️ Umbrella','🔋 Power bank'];
let ps=JSON.parse(localStorage.getItem('hk-prep-v2')||'{}');const pc=document.getElementById('tripcheck');pc.innerHTML=prep.map((x,i)=>`<label><input type="checkbox" data-i="${i}" ${ps[i]?'checked':''}> ${x}</label>`).join('');
function prepMeter(){const n=prep.filter((_,i)=>ps[i]).length;document.getElementById('prepText').textContent=`${n} / ${prep.length} พร้อม`;document.getElementById('prepBar').style.width=(n/prep.length*100)+'%'}
pc.querySelectorAll('input').forEach(x=>x.onchange=()=>{ps[x.dataset.i]=x.checked;localStorage.setItem('hk-prep-v2',JSON.stringify(ps));prepMeter()});prepMeter();
document.querySelectorAll('a[href="../"]').forEach(a=>a.onclick=e=>{e.preventDefault();document.body.style.transition='opacity .3s';document.body.style.opacity='0';setTimeout(()=>location.href='../',280)});addEventListener('pageshow',()=>document.body.style.opacity='1');