const UA='Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/131 Safari/537.36';
const MIN_NIGHTLY=700;
function clean(s){return String(s||'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ')}
function date(v){return /^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):''}
function nights(a,b){if(!a||!b)return 0;const x=new Date(a+'T00:00:00Z'),y=new Date(b+'T00:00:00Z'),n=Math.round((y-x)/86400000);return n>0&&n<31?n:0}
async function text(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{headers:{'User-Agent':UA,'Accept-Language':'en-US,en;q=.9'},cf:{cacheTtl:0,cacheEverything:false},signal:c.signal});if(!r.ok)throw new Error('HTTP_'+r.status);return await r.text()}finally{clearTimeout(t)}}
function thbEntries(html){const s=clean(html).replace(/\\u0e3f/gi,'฿'),o=[];for(const re of [/(?:THB\s*|฿\s*)([0-9][0-9,.]*)/gi,/([0-9][0-9,.]*)\s*THB/gi]){let m;while((m=re.exec(s))){const v=Number(m[1].replace(/,/g,''));if(v>=300&&v<=200000)o.push({v,p:m.index})}}return o.sort((a,b)=>a.p-b.p)}
function pair(entries,n){const c=[];for(let i=0;i<entries.length;i++){const a=entries[i];if(a.v<MIN_NIGHTLY||a.v>30000)continue;for(let j=i+1;j<Math.min(entries.length,i+18);j++){const b=entries[j],dist=b.p-a.p;if(dist>1600)break;if(b.v<=a.v)continue;const implied=b.v/n,ratio=b.v/(a.v*n);if(implied<MIN_NIGHTLY||implied>30000)continue;if(ratio<.92||ratio>1.30)continue;c.push({total:b.v,nightly:Math.round(b.v/n),score:Math.abs(ratio-1.06)+dist/16000})}}return c.sort((a,b)=>a.score-b.score||a.total-b.total)[0]||null}
function cny(html){const s=clean(html),vals=[];for(const re of [/(?:CNY|RMB|¥|￥)\s*([0-9][0-9,.]*)/gi,/([0-9][0-9,.]*)\s*(?:CNY|RMB)/gi]){let m;while((m=re.exec(s))){const v=Number(m[1].replace(/,/g,''));if(v>=300&&v<=1200)vals.push(v)}}return[...new Set(vals)].sort((a,b)=>a-b)}
async function fx(){try{const r=await fetch('https://open.er-api.com/v6/latest/THB',{cf:{cacheTtl:0,cacheEverything:false}}),d=await r.json(),v=Number(d?.rates?.CNY);return{status:v>0?'live':'unavailable',source:'ExchangeRate-API',ratesToTHB:{THB:1,CNY:v>0?1/v:null},updatedAt:d?.time_last_update_utc||null}}catch{return{status:'unavailable',ratesToTHB:{THB:1,CNY:null}}}}
async function hotel(h){const start=date(h.start),end=date(h.end),n=nights(start,end),base={tripId:'shanghai',name:String(h.name||'').slice(0,140),start,end,nights:n};if(!n)return{...base,status:'needs_dates',message:'Set travel dates first'};const q=new URLSearchParams({q:base.name,checkin:start,checkout:end,adults:'2',currency:'THB',hl:'en',gl:'th'}),sourceUrl='https://www.google.com/travel/hotels?'+q;try{const html=await text(sourceUrl),p=pair(thbEntries(html),n);if(!p)return{...base,status:'unavailable',source:'Google Hotels',sourceUrl,message:'Could not verify a consistent stay total'};return{...base,status:'live',source:'Google Hotels',sourceUrl,currency:'THB',nightlyTHB:p.nightly,totalTHB:Math.round(p.total),estimatedTotal:false,priceType:'verified_pair',verification:'paired_total'}}catch(e){return{...base,status:'unavailable',source:'Google Hotels',sourceUrl,error:String(e?.message||e)}}}
async function ticket(rate){const url='https://www.shanghaidisneyresort.com/en';try{const vals=cny(await text(url));if(!vals.length)return{tripId:'shanghai',id:'shanghai-disney',name:'Shanghai Disneyland 1-Day Ticket',status:'unavailable',source:'Shanghai Disney Resort Official',sourceUrl:url};const r=Number(rate)||0;return{tripId:'shanghai',id:'shanghai-disney',name:'Shanghai Disneyland 1-Day Ticket',status:'live',source:'Shanghai Disney Resort Official',sourceUrl:url,currency:'CNY',listedPrices:vals.slice(0,10),minPrice:vals[0],maxPrice:vals[vals.length-1],minTHB:r?Math.round(vals[0]*r):null,maxTHB:r?Math.round(vals[vals.length-1]*r):null,priceType:'current_listed_range'}}catch(e){return{tripId:'shanghai',id:'shanghai-disney',name:'Shanghai Disneyland 1-Day Ticket',status:'unavailable',source:'Shanghai Disney Resort Official',sourceUrl:url,error:String(e?.message||e)}}}
export async function handleShanghaiPrices(req,url,origin,json,allowed){if(url.pathname!=='/api/prices/refresh'||req.method!=='POST')return null;let body={};try{body=await req.clone().json()}catch{return null}const ids=Array.isArray(body.tripIds)?body.tripIds.map(String):[];if(ids.length!==1||ids[0]!=='shanghai')return null;if(!allowed(origin))return json({ok:false,error:'forbidden_origin'},403,origin);const checkedAt=new Date().toISOString(),f=await fx(),hs=(Array.isArray(body.hotels)?body.hotels:[]).filter(h=>h?.tripId==='shanghai'&&h?.name).slice(0,6),hotels=await Promise.all(hs.map(hotel)),tickets=[await ticket(f.ratesToTHB?.CNY)];return json({ok:true,checkedAt,fx:f,hotels,tickets,meta:{hotelSource:'Google Hotels with consistency validation',ticketSource:'Shanghai Disney Resort Official',note:'Shanghai-only refresh. Unverified prices are not guessed.'}},200,origin)}