(()=>{
'use strict';
const API='https://travel-hub-api.mlrkdee44.workers.dev',STATE='travelHubStateV2',TT='travelToolsV1',PRICE='travelHubTripPricesV1';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const load=(k,d={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const valid=d=>/^\d{4}-\d{2}-\d{2}$/.test(String(d||''));
const addDays=(d,n)=>{if(!valid(d))return'';const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dates(){const st=load(STATE,{}),tt=load(TT,{}),s=st.shanghai||st.trips?.shanghai||{},start=s.start||tt.dates?.shanghai||'',end=s.end||addDays(start,4);return{start:valid(start)?start:'',end:valid(end)?end:addDays(start,4)}}
function booking(name){const d=dates(),q=new URLSearchParams({ss:name,group_adults:'2',no_rooms:'1',group_children:'0',selected_currency:'THB'});if(d.start&&d.end){q.set('checkin',d.start);q.set('checkout',d.end)}return'https://www.booking.com/searchresults.html?'+q}
function hotelCard(h){return `<article class="card hotelcard" data-hotel="${esc(h.name)}"><img src="${h.img}" alt="${esc(h.name)}"><div class="pad"><div class="ey">${h.ey}</div><h3>${esc(h.name)}</h3><p>${esc(h.loc)}</p><div class="hotelmeta"><span class="badge good">⭐ ${esc(h.score)}</span><span class="badge">${esc(h.brand)}</span></div><div class="sidebox hotelprice">ยังไม่ได้เช็กราคาตามวันที่จริง</div><div class="muted small">${esc(h.desc)}</div><a class="map" target="_blank" rel="noopener" href="${A(h.map)}">📍 Amap</a> <a class="map book" target="_blank" rel="noopener" href="${booking(h.name)}">🏨 Booking</a></div></article>`}
function renderHotels(){const g=$('#hotelGrid');if(!g)return;g.innerHTML=HOTELS.map(hotelCard).join('')}
const tagName={must:'⭐ Must Ride',hot:'🔥 ฮิตมาก',thrill:'🎢 Thrill',family:'👨‍👩‍👧 Family'};
let ds=load('shanghai-disney-attractions-v1',{});
function rideCard(r){const v=ds[r.id]||{};return `<article class="ride" data-ride="${r.id}"><div class="ridebody"><div class="ridezone">${r.z}</div><h4>${r.n}</h4><div class="tags">${(r.cat||[]).map(c=>`<span class="tag ${c}">${tagName[c]}</span>`).join('')}</div><div class="rideflags"><button class="toggle want ${v.want?'on':''}" data-type="want">⭐ อยากเล่น</button><button class="toggle done ${v.done?'on':''}" data-type="done">✅ เล่นแล้ว</button></div></div></article>`}
function disneyHTML(){return `<section class="disneybox" id="disney"><div class="disneytop"><div><div class="ey">DISNEY CHECKLIST • ${DISNEY_RIDES.length} ITEMS</div><h3>🎢 Shanghai Disneyland</h3><div class="small muted">ใช้ checklist แบบเดียวกับทริป Hong Kong • เช็กคิวจริงใน Shanghai Disney app</div></div><div class="meter"><span id="rideCount">0/${DISNEY_RIDES.length}</span><div class="track"><i id="rideBar"></i></div></div></div><div class="rides">${DISNEY_RIDES.map(rideCard).join('')}</div><div class="hint">↔ ปัดเพื่อดูเครื่องถัดไป • เวลาเปิด/โชว์ให้เช็กวันจริง</div></section>`}
function rideMeter(){const n=DISNEY_RIDES.filter(r=>ds[r.id]?.done).length;if($('#rideCount'))$('#rideCount').textContent=`${n}/${DISNEY_RIDES.length}`;if($('#rideBar'))$('#rideBar').style.width=(n/DISNEY_RIDES.length*100)+'%'}
function dayCard(x,i){return `<article class="card day ${i===0?'open':''}" id="day${i+1}"><button class="daybtn"><img src="${IMG[x.i]}" alt="${esc(x.t)}"><div><div class="ey">${x.d}</div><h3>${x.t}</h3></div><span class="chev">⌄</span></button><div class="body"><div class="inside"><div class="innerpad"><img class="dayhero" src="${IMG[x.i]}" alt="${esc(x.t)}"><div class="cols"><div class="timeline">${x.s.map(z=>`<div class="step"><div class="time">${z[0]}</div><div class="place">${z[1]}</div><div class="small muted">${z[3]}</div><a class="map" target="_blank" rel="noopener" href="${A(z[2])}">📍 Amap</a>${z[4]?`<button class="routebtn">${z[4]} ▾</button><div class="route"><div><div class="routecard">${z[5]}</div></div></div>`:''}</div>`).join('')}</div><div><span class="cost">💰 ${x.cost}</span><div class="sidebox"><b>🇨🇳 China Transit Tip</b><div class="small muted">ใช้ Amap เป็นหลัก และเช็ก Metro / DiDi ตามเวลาจริงก่อนออกจากแต่ละจุด</div></div>${i===1?`<div class="sidebox"><b>🎟️ Official Ticket</b><div class="small muted" id="ticketPrice">ยังไม่ได้เช็กราคาสด</div><a class="map" target="_blank" rel="noopener" href="https://www.shanghaidisneyresort.com/en">Shanghai Disney Official</a></div>`:''}</div></div>${i===1?disneyHTML():''}</div></div></div></article>`}
function renderTrip(){const d=$('#daysbox');if(d)d.innerHTML=DAYS.map(dayCard).join('');rideMeter()}
function paintDates(){const d=dates();if($('#tripDateText'))$('#tripDateText').textContent=d.start?`5 Days 4 Nights • ${d.start} → ${d.end}`:'5 Days 4 Nights • Shanghai • รอเลือกวันที่เดินทาง';$$('[data-hotel]').forEach(h=>{const b=$('.book',h);if(b)b.href=booking(h.dataset.hotel)})}
function renderSaved(){const d=load(PRICE,{}).shanghai;if(d)renderPrices(d)}
function renderPrices(data){const hotels=Array.isArray(data?.hotels)?data.hotels:[];$$('[data-hotel]').forEach(card=>{const r=hotels.find(x=>x.name===card.dataset.hotel),box=$('.hotelprice',card);if(!box)return;if(r?.status==='live'&&Number(r.totalTHB)>0){const nights=Number(r.nights)||4,nightly=Number(r.nightlyTHB)||Math.round(Number(r.totalTHB)/nights);box.innerHTML=`<span class="priceok">LIVE • ฿${Number(r.totalTHB).toLocaleString('en-US')} / ${nights} คืน</span><div class="small muted">เฉลี่ย ฿${nightly.toLocaleString('en-US')}/คืน • ${esc(r.source||'verified source')}</div>`}else if(r?.status==='needs_dates'){box.innerHTML='<span class="warn">ตั้งวันที่เดินทางก่อน</span>'}else if(r){box.innerHTML='<span class="warn">ยังยืนยันราคาสดไม่ได้</span><div class="small muted">ไม่แสดงราคาที่ตรวจสอบความสอดคล้องไม่ได้</div>'}});const t=Array.isArray(data?.tickets)?data.tickets[0]:null;if($('#ticketPrice')&&t?.status==='live')$('#ticketPrice').textContent=t.minTHB&&t.maxTHB?`LIVE • ประมาณ ฿${Number(t.minTHB).toLocaleString()}–฿${Number(t.maxTHB).toLocaleString()} • Official`:`LIVE • CNY ${t.minPrice}–${t.maxPrice} • Official`;else if($('#ticketPrice')&&t)$('#ticketPrice').textContent='ยังยืนยันราคาสดไม่ได้จาก Official';if(data?.checkedAt&&$('#checkedAt'))$('#checkedAt').textContent='LAST CHECKED • '+new Date(data.checkedAt).toLocaleString('th-TH')}
async function refresh(){const b=$('#refreshBtn'),d=dates();if(!d.start||!d.end){b.textContent='ตั้งวันที่ก่อน';setTimeout(()=>b.textContent='↻ เช็กราคา',1500);openSettings();return}b.disabled=true;b.textContent='กำลังเช็ก…';try{const hotels=HOTELS.map(x=>({tripId:'shanghai',name:x.name,start:d.start,end:d.end}));const r=await fetch(API+'/api/prices/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tripIds:['shanghai'],hotels})});const data=await r.json();if(!r.ok||!data?.ok)throw new Error(data?.error||'refresh failed');const all=load(PRICE,{});all.shanghai=data;save(PRICE,all);renderPrices(data)}catch(e){if($('#checkedAt'))$('#checkedAt').textContent='เช็กราคาไม่สำเร็จ • ลองใหม่ภายหลัง'}finally{b.disabled=false;b.textContent='↻ เช็กราคา'}}
function openSettings(){const t=$('#tt-launch');if(t){t.click();setTimeout(()=>document.querySelector('[data-tt-settings],.tt-settings,.tt-tab[data-tab="settings"]')?.click(),90)}else location.href='../#trip-tools'}
function prep(){let ps=load('shanghai-prep-v1',{}),pc=$('#tripcheck');if(!pc)return;pc.innerHTML=PREP.map((x,i)=>`<label><input type="checkbox" data-i="${i}" ${ps[i]?'checked':''}> ${x}</label>`).join('');const meter=()=>{const n=PREP.filter((_,i)=>ps[i]).length;$('#prepText').textContent=`${n} / ${PREP.length} พร้อม`;$('#prepBar').style.width=(n/PREP.length*100)+'%'};pc.querySelectorAll('input').forEach(x=>x.onchange=()=>{ps[x.dataset.i]=x.checked;save('shanghai-prep-v1',ps);meter()});meter()}
renderHotels();renderTrip();paintDates();renderSaved();prep();
document.addEventListener('click',e=>{const db=e.target.closest('.daybtn');if(db){db.parentElement.classList.toggle('open');return}const rb=e.target.closest('.routebtn');if(rb){rb.nextElementSibling.classList.toggle('open');return}const t=e.target.closest('.toggle');if(t){const ride=t.closest('[data-ride]')?.dataset.ride;if(!ride)return;ds[ride]=ds[ride]||{};ds[ride][t.dataset.type]=!ds[ride][t.dataset.type];save('shanghai-disney-attractions-v1',ds);$$(`[data-ride="${ride}"] [data-type="${t.dataset.type}"]`).forEach(x=>x.classList.toggle('on',ds[ride][t.dataset.type]));rideMeter()}});
$('#refreshBtn')?.addEventListener('click',refresh);$('#settingsBtn')?.addEventListener('click',openSettings);
window.addEventListener('storage',e=>{if(e.key===STATE||e.key===TT){paintDates();renderHotels();renderSaved()}});
document.querySelectorAll('a[href="../"]').forEach(a=>a.onclick=e=>{e.preventDefault();document.body.style.transition='opacity .3s';document.body.style.opacity='0';setTimeout(()=>location.href='../',280)});addEventListener('pageshow',()=>document.body.style.opacity='1');
})();
